---
dockitems_remove:
- Mail
- Messages
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Reminders
- Freeform
- TV
- Music
- News
- Notes
- 'Keynote'
- 'Numbers'
- 'Pages'
- 'App Store'
- 'iPhone Mirroring'

dockitems_persist:
- name: Launchpad
  path: "/System/Applications/Launchpad.app/"
  pos: 1
- name: "Safari"
  path: "/Applications/Safari.app/"
  pos: 2
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
  pos: 3
- name: 1Password
  path: "/Applications/1Password.app/"
  pos: 4
- name: Ghostty
  path: "/Applications/Ghostty.app/"
  pos: 5
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 6
- name: "BBEdit"
  path: "/Applications/BBEdit.app/"
  pos: 7
- name: UTM
  path: "/Applications/UTM.app"
  pos: 8
- name: Transmission
  path: "/Applications/Transmission.app"
  pos: 9