---
# Dotfiles
dotfiles_repo: 'https://github.com/glennbrown/dotfiles.git'
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .aliases
  - .bashrc
  - .bash_profile
  - .config/starship.toml
  - .config/ghostty
  - .inputrc
  - .vimrc
  - .zshrc
  - .zprofile