---
# Mac App Store
mas_installed_apps:
# Safari Extensions
- { id: 1569813296, name: "1Password for Safari" }
- { id: 1662217862, name: "Wipr" }
# Media
- { id: 510620098, name: "MediaInfo" }
# Tools
- { id: 1168254295, name: "AmorphousDiskMark" }
- { id: 1492174677, name: "Text Case" }
- { id: 1160435653, name: AutoMounter }
- { id: 6739505345, name: Hyperspace }