services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:2.9.0
    container_name: smokeping
    hostname: heimdall
    environment:
      TZ: {{ ntp_timezone }}
      PUID: {{ me.uid }}
      PGID: {{ me.gid }}
    volumes:
      - {{ appdata_path }}/smokeping/config:/config
      - {{ appdata_path }}/smokeping/data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.{{ local_domain }}`)"
      - "traefik.http.routers.smokeping.tls=true"
      - "traefik.http.routers.smokeping.tls.certresolver=cloudflare"

  beszel:
    image: henrygd/beszel:0.15.4
    container_name: beszel
    hostname: beszel
    environment:
      TZ: {{ ntp_timezone }}
    volumes:
      - {{ appdata_path }}/beszel/beszel_data:/beszel_data
      - {{ appdata_path }}/beszel/beszel_socket:/beszel_socket
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.{{ local_domain }}`)"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.routers.beszel.tls.certresolver=cloudflare"

  beszel-agent:
    image: henrygd/beszel-agent:0.13.2
    container_name: beszel-agent
    environment:
      LISTEN: 45876
      KEY: {{ thor_agent_key }}
      TOKEN: {{ thor_agent_token }}
      HUB_URL: https://beszel.home.ikgb.me
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - {{ appdata_path }}/beszel/beszel_agent_data:/var/lib/beszel-agent
    restart: unless-stopped
    