services:
  traefik:
    image: traefik:v3.6.0
    container_name: traefik
    environment:
      TZ: {{ ntp_timezone }}
      CF_DNS_API_TOKEN: {{ cloudflare_traefik_api_token }}
    volumes:
      - {{ traefik_data_path }}/config:/config
      - {{ traefik_data_path }}/letsencrypt:/letsencrypt
      - {{ traefik_data_path }}/.htpasswd:/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    command:
      - --log.level=info
      - --api.insecure=false
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/config
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    extra_hosts:
      - host.docker.internal:172.17.0.1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`thor.{{ local_domain }}`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/.htpasswd"
      